### PR TITLE
Fixed scraping to latest metacritic website

### PR DESCRIPTION
**Pull request by harvinb**
Scraping was not working well on latest metacritic site.
Please review changes

### CODE REVIEW

**Comment by ig3io** [comment]
As soon as I have time I'll review the changes! :)

**Comment by harvinb** [comment]
Hi, 

I added some more commits to implement search functionality... I did not know that making a commit to the same branch would add it to the pull request (I am new to git).
I can resubmit a pull request with only the original fixes from another branch

**Comment by ig3io** [comment]
Yeah! It'll be better if the changes to review have their own branch! Thanks!

**Comment by harvinb** [comment]
Sure! I will do that! 
Thanks for your time!

**Pull request closed without merging**
